### PR TITLE
Generation of Italian Fiscal Code

### PR DESCRIPTION
**Pull request by supix**

### CODE REVIEW

**Review by AdmiringWorm — APPROVED** [review]
LGTM 👍

**Comment by AdmiringWorm** [comment]
hmm, looks like the linux build fails. I'll need to check it out, don't think there is anything wrong from your part. Probably just travis that messes up something.

**Comment by AdmiringWorm** [comment]
yup, seems to be just a problem with the build server.
I'm happy to merge this whenever you are ready.

**Comment by supix** [comment]
@AdmiringWorm Ok for me. Thanks Kim.

**Comment by AdmiringWorm** [comment]
👍

**Comment by AdmiringWorm** [comment]
Now I only need to complete the new build system I'm testing out,
and get started on a beer generator and I'll be able to push out a new release.
But that will be continued on tomorrow

**Comment by AdmiringWorm** [comment]
If you have something you want implemented, feel free to open up an issue.

**Comment by AdmiringWorm** [comment]
@supix version 2.4.0 is now available on nuget.org, unfortunately I made a mistake with the
build script so the italian culture was not added this time.
I've logged it in issue #34 for now, and will push out a fixed release when I got time.

**Comment by supix** [comment]
@AdmiringWorm Thanks a lot for the great job, Kim. No problem for the missing translation.

**Comment by AdmiringWorm** [comment]
I've already added a new version on nuget which contains the missing translation.
Thank you for all the great code you have added to the library for this release, as well as the translation.
Those code related tasks was something that had bothered me for quite some time, but never knew how
to implement those

**Comment by supix** [comment]
@AdmiringWorm My pleasure. It is nice to work in a so accurate and well-designed codebase. Also learning some new development and continuous-integration tools.

**Comment by AdmiringWorm** [comment]
I'm glad you think so, well well-designed might not be entirely correct though.
A library just containing static methods is generally considered bad practice,
but since the original [faker-cs](https://github.com/slashdotdash/faker-cs) also used just static method
I didn't really want to change that.
This project originally started out as just a fork of that one, and was intended to be a
drop-in replacement for users who needed a portable library.

On that note though, a future plan of mine is to start another Faker library project,
which will get rid of static methods, add support for .NET Core and changing from
resx resources to json instead.
But that is just in planning stage at the moment while working on some other projects.

**Comment by supix** [comment]
@AdmiringWorm Ok as far as portability (and so JSON). Get rid of static classes? Something like (I don't like it)

var name = new Name();
name.First();

…or what?

Static classes are an anti-pattern when you need state. It seems not the case to me.

**Comment by AdmiringWorm** [comment]
I'm still thinking about how to model that library, but it won't be like you have to instantiate each class
yourself, you would create the main instance with the culture to use for that all
its subclasses (or however I will model them) and cache the resources located the in the json files
per instance.

What I'm thinking is for example something like this:

``` cs
var faker = new Faker("en-US");

var firstName = faker.Name.First();
```

the Name being a property of a `NameGenerator` class or something which will be lazy initialized.

But as I said, that will be for another library, the Faker.Net.Portable will still stay as it is
with its static classes and methods.

**Comment by supix** [comment]
@AdmiringWorm Ok. Does make sense. Actually, it would also solve more naturally some headhaches (e.g. lazy loaded cached resources...).

**Pull request merged**
