### PR TITLE
Add Random Boolean 

### LINKED ISSUE #42: Add random Boolean to the project
## Expected Behavior
Should randomly return True or False

## Current Behavior
Doesn't exist 

## Context
Have to assign a random number == 1 to false

### PR DESCRIPTION
**Pull request by sparhawk9**
## Description
Adds a random Boolean to the project.

## Motivation and Context
I needed to have a random boolean for testing.
fixes #42 
## How Has This Been Tested?
Added a unit test to the project for all new methods

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by AdmiringWorm — APPROVED** [review]
LGTM,
as soon as you are able to sign the CLA I can get this merged, and released.

**Comment by AdmiringWorm** [comment]
Seems like it will take a little time for me to get this PR merged, I have a few build errors that I need to resolve before I can do that.

**Comment by sparhawk9** [comment]
Hopefully nothing I caused.

On Nov 27, 2017 10:29 AM, "Kim J. Nordmo" <notifications@github.com> wrote:

Seems like it will take a little time for me to get this PR merged, I have
a few build errors that I need to resolve before I can do that.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/WormieCorp/Faker.NET.Portable/pull/43#issuecomment-347216991>,
or mute the thread

**Comment by AdmiringWorm** [comment]
No worries, it's not your fault.
It's a build failure I had quite a long time now, just never bothered to fix it.

**Comment by AdmiringWorm** [comment]
This pr was merged in https://github.com/WormieCorp/Faker.NET.Portable/commit/9eb3c96d001cf6e6fba3c63a9924e55246ad5b95 , unfortunately due to an error on my part this PR wasn't closed.

I expect to be able to create a new release this weekend, just working on migrating the wiki to make use of wyam before I create a release.

**Comment by AdmiringWorm** [comment]
this is now available in the newly pushed 2.6.0 release

**Pull request closed without merging**
